/**
 * Machine-readable error codes returned by the API.
 *
 * The mobile app maps these codes to localized strings via `ErrorMapper`.
 * Never change an existing code value — doing so breaks client-side localization.
 *
 * When adding a new code:
 *  1. Append it here with a unique value.
 *  2. Add the matching localization key to the mobile ARB files.
 *  3. Update ErrorMapper in the mobile app.
 */
export enum ErrorCode {
  // Generic
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  DATABASE_ERROR = 'DATABASE_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',

  // Auth
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  ACCOUNT_DELETED = 'ACCOUNT_DELETED',
  OAUTH_REQUIRED = 'OAUTH_REQUIRED',
  DUPLICATE_EMAIL = 'DUPLICATE_EMAIL',
  INVALID_OPERATION = 'INVALID_OPERATION',
  RATE_LIMITED = 'RATE_LIMITED',

  // Subscription / Business
  TRIAL_EXPIRED = 'TRIAL_EXPIRED',
  LIMIT_REACHED = 'LIMIT_REACHED',
  UPGRADE_REQUIRED = 'UPGRADE_REQUIRED',

  // User
  EMAIL_IN_USE = 'EMAIL_IN_USE',
  INVALID_PASSWORD = 'INVALID_PASSWORD',

  // BabyMon
  BABYMON_NOT_FOUND = 'BABYMON_NOT_FOUND',

  // Milestones
  MILESTONE_NOT_FOUND = 'MILESTONE_NOT_FOUND',

  // Feed Logs
  FEED_LOG_NOT_FOUND = 'FEED_LOG_NOT_FOUND',

  // Health Records
  HEALTH_RECORD_NOT_FOUND = 'HEALTH_RECORD_NOT_FOUND',

  // Allergies
  ALLERGY_NOT_FOUND = 'ALLERGY_NOT_FOUND',
  ALLERGY_EVENT_NOT_FOUND = 'ALLERGY_EVENT_NOT_FOUND',
  ALLERGY_ALREADY_CURED = 'ALLERGY_ALREADY_CURED',
  ALLERGY_ALREADY_ACTIVE = 'ALLERGY_ALREADY_ACTIVE',

  // Growth
  GROWTH_RECORD_NOT_FOUND = 'GROWTH_RECORD_NOT_FOUND',
  GROWTH_RECORD_UNAUTHORIZED = 'GROWTH_RECORD_UNAUTHORIZED',

  // Sleep
  SLEEP_LOG_NOT_FOUND = 'SLEEP_LOG_NOT_FOUND',
  SLEEP_LOG_UNAUTHORIZED = 'SLEEP_LOG_UNAUTHORIZED',

  // Media
  MEDIA_NOT_FOUND = 'MEDIA_NOT_FOUND',
  MEDIA_UNAUTHORIZED = 'MEDIA_UNAUTHORIZED',
  MEDIA_INVALID_TYPE = 'MEDIA_INVALID_TYPE',
  MEDIA_TOO_LARGE = 'MEDIA_TOO_LARGE',
  INVALID_FILE_TYPE = 'INVALID_FILE_TYPE',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',

  // Companion / Routine / Model
  ROUTINE_NOT_FOUND = 'ROUTINE_NOT_FOUND',
  COMPANION_NOT_FOUND = 'COMPANION_NOT_FOUND',
  COMPANION_UNAUTHORIZED = 'COMPANION_UNAUTHORIZED',
  MODEL_NOT_CONFIGURED = 'MODEL_NOT_CONFIGURED',
  MODEL_DOWNLOAD_FAILED = 'MODEL_DOWNLOAD_FAILED',

  // Journal / Proposals
  PROPOSAL_NOT_FOUND = 'PROPOSAL_NOT_FOUND',
  PROPOSAL_ALREADY_RESOLVED = 'PROPOSAL_ALREADY_RESOLVED',
  JOURNAL_PROPOSAL_NOT_FOUND = 'JOURNAL_PROPOSAL_NOT_FOUND',
  JOURNAL_PROPOSAL_UNAUTHORIZED = 'JOURNAL_PROPOSAL_UNAUTHORIZED',
  JOURNAL_NOT_FOUND = 'JOURNAL_NOT_FOUND',
  JOURNAL_UNAUTHORIZED = 'JOURNAL_UNAUTHORIZED',

  // Export
  EXPORT_NO_DATA = 'EXPORT_NO_DATA',

  // S3 / Infrastructure
  S3_NOT_CONFIGURED = 'S3_NOT_CONFIGURED',

  // Partners / Linked Accounts
  INVITATION_NOT_FOUND = 'INVITATION_NOT_FOUND',
  CANNOT_INVITE_SELF = 'CANNOT_INVITE_SELF',
  INVITATION_ALREADY_PROCESSED = 'INVITATION_ALREADY_PROCESSED',
  INVITATION_EXPIRED = 'INVITATION_EXPIRED',
  LINK_NOT_FOUND = 'LINK_NOT_FOUND',
  PARTNER_UNAUTHORIZED = 'PARTNER_UNAUTHORIZED',

  // Promo Codes
  PROMO_CODE_INVALID = 'PROMO_CODE_INVALID',
  PROMO_CODE_EXPIRED = 'PROMO_CODE_EXPIRED',
  PROMO_CODE_LIMIT_REACHED = 'PROMO_CODE_LIMIT_REACHED',
  PROMO_CODE_ALREADY_USED = 'PROMO_CODE_ALREADY_USED',

  // Evolution
  EVOLUTION_NOT_FOUND = 'EVOLUTION_NOT_FOUND',
  EVOLUTION_UNAUTHORIZED = 'EVOLUTION_UNAUTHORIZED',

  // Stage Content
  STAGE_CONTENT_NOT_FOUND = 'STAGE_CONTENT_NOT_FOUND',

  // Admin
  ADMIN_UNAUTHORIZED = 'ADMIN_UNAUTHORIZED',
  ADMIN_USER_NOT_FOUND = 'ADMIN_USER_NOT_FOUND',

  // Stripe
  STRIPE_NOT_CONFIGURED = 'STRIPE_NOT_CONFIGURED',
  STRIPE_SUBSCRIPTION_NOT_FOUND = 'STRIPE_SUBSCRIPTION_NOT_FOUND',
  STRIPE_WEBHOOK_INVALID = 'STRIPE_WEBHOOK_INVALID',
}
