import { PrismaClient, MilestoneDomain, MilestoneStatus } from '@prisma/client';
const prisma = new PrismaClient();

export async function seedMoreMilestones() {
  console.log('Seeding 40 additional milestone expectations...');
  const milestones = [
    // ─── Pregnancy: sensory & reflex development ───
    { stageKey: 'preg_week_5', domain: 'GROSS_MOTOR' as MilestoneDomain, title: 'Heart Tube Forms', description: 'The primitive heart tube begins to loop and fold, forming the early chambers that will become a four-chamber heart.', status: 'EXPECTED' as MilestoneStatus, activityPrompt: 'Place your hand over your heart and imagine the tiny pulse beginning inside you.', xpReward: 15 },
    { stageKey: 'preg_week_5', domain: 'COGNITIVE' as MilestoneDomain, title: 'Neural Tube Closes', description: 'The neural tube — the foundation of the brain and spinal cord — completes its closure this week.', status: 'EXPECTED' as MilestoneStatus, activityPrompt: 'Take your folic acid supplement if you have not already — it supports this critical process.', xpReward: 15 },
    { stageKey: 'preg_week_8', domain: 'FINE_MOTOR' as MilestoneDomain, title: 'Finger Rays Visible', description: 'The hand plates are developing digital rays — the earliest outlines of fingers and thumbs.', status: 'EXPECTED' as MilestoneStatus, activityPrompt: 'Look at your own hands and imagine the tiny blueprint forming within your baby.', xpReward: 15 },
    { stageKey: 'preg_week_8', domain: 'LANGUAGE_COMMUNICATION' as MilestoneDomain, title: 'Inner Ear Structures Form', description: 'The cochlea and vestibular system begin developing, laying the foundation for hearing and balance.', status: 'EXPECTED' as MilestoneStatus, activityPrompt: 'Play gentle music and speak softly — your baby will hear you in a few more weeks.', xpReward: 15 },
    { stageKey: 'preg_week_10', domain: 'GROSS_MOTOR' as MilestoneDomain, title: 'Spontaneous Movement Begins', description: 'Your fetus makes the first spontaneous movements — tiny arcs and startles not yet felt.', status: 'EXPECTED' as MilestoneStatus, activityPrompt: 'Know that your baby is already stretching and moving, even though you cannot feel it yet.', xpReward: 15 },
    { stageKey: 'preg_week_12', domain: 'FINE_MOTOR' as MilestoneDomain, title: 'Fingers and Toes Separate', description: 'The webbed digits have separated into distinct fingers and toes with soft nails forming.', status: 'EXPECTED' as MilestoneStatus, activityPrompt: 'Count your own fingers and toes — your baby now has all ten of each.', xpReward: 15 },
    { stageKey: 'preg_week_14', domain: 'COGNITIVE' as MilestoneDomain, title: 'Suck-and-Swallow Practice Begins', description: 'Your fetus begins practicing the suck-and-swallow coordination essential for feeding after birth.', status: 'EXPECTED' as MilestoneStatus, activityPrompt: 'Notice your own swallow reflex — your baby is already practicing this vital skill.', xpReward: 15 },
    { stageKey: 'preg_week_16', domain: 'LANGUAGE_COMMUNICATION' as MilestoneDomain, title: 'Hearing Structures Mature', description: 'The bones of the middle ear are hardening, and the auditory pathways to the brain are forming.', status: 'EXPECTED' as MilestoneStatus, activityPrompt: 'Talk, read aloud, or sing — by next month your baby will begin to detect sounds.', xpReward: 15 },
    { stageKey: 'preg_week_18', domain: 'SOCIAL_EMOTIONAL' as MilestoneDomain, title: 'First Sleep-Wake Cycles', description: 'Your fetus develops recognizable periods of activity and rest, the earliest circadian patterns.', status: 'EXPECTED' as MilestoneStatus, activityPrompt: 'Track when you feel the most movement — your baby may have active and quiet times.', xpReward: 15 },
    { stageKey: 'preg_week_22', domain: 'FINE_MOTOR' as MilestoneDomain, title: 'Grasp Reflex Develops', description: 'Your baby can now grasp their own umbilical cord and may bring hands to face.', status: 'EXPECTED' as MilestoneStatus, activityPrompt: 'Gently press on your belly and see if your baby pushes back — early two-way communication.', xpReward: 15 },
    { stageKey: 'preg_week_24', domain: 'SOCIAL_EMOTIONAL' as MilestoneDomain, title: 'Responds to Familiar Voices', description: 'Your baby\'s brain can now distinguish and respond to familiar voices, especially yours.', status: 'EXPECTED' as MilestoneStatus, activityPrompt: 'Have your partner or older child talk to your belly — your baby can hear and remember.', xpReward: 15 },
    { stageKey: 'preg_week_26', domain: 'COGNITIVE' as MilestoneDomain, title: 'REM Sleep Established', description: 'Your baby now cycles through REM and non-REM sleep, and may even dream.', status: 'EXPECTED' as MilestoneStatus, activityPrompt: 'Rest when your baby rests — your sleep patterns are beginning to synchronize.', xpReward: 15 },
    { stageKey: 'preg_week_30', domain: 'LANGUAGE_COMMUNICATION' as MilestoneDomain, title: 'Recognizes Mother\'s Language', description: 'Studies show newborns prefer the rhythm and melody of their mother\'s language, learned in utero.', status: 'EXPECTED' as MilestoneStatus, activityPrompt: 'Read aloud from the same book each night — your baby will recognize the rhythm after birth.', xpReward: 15 },
    { stageKey: 'preg_week_32', domain: 'FINE_MOTOR' as MilestoneDomain, title: 'Thumb Sucking Visible on Ultrasound', description: 'Many babies suck their thumbs in utero, self-soothing and practicing the suck reflex.', status: 'EXPECTED' as MilestoneStatus, activityPrompt: 'At your next ultrasound, ask if you can see your baby\'s hands near their face.', xpReward: 15 },
    { stageKey: 'preg_week_34', domain: 'SOCIAL_EMOTIONAL' as MilestoneDomain, title: 'Responsive to External Touch', description: 'Your baby responds to gentle pressure on your belly — pushing back or shifting position.', status: 'EXPECTED' as MilestoneStatus, activityPrompt: 'Play a gentle press-and-release game: press softly and wait for a response.', xpReward: 15 },
    { stageKey: 'preg_week_38', domain: 'COGNITIVE' as MilestoneDomain, title: 'Memory for Sounds Established', description: 'Your baby now remembers and prefers familiar sounds — your voice, a song, a story pattern.', status: 'EXPECTED' as MilestoneStatus, activityPrompt: 'Sing the same lullaby each night — this will be a powerful comfort tool after birth.', xpReward: 15 },
    // ─── Newborn weeks: early reflexes & responses ───
    { stageKey: 'born_week_2', domain: 'GROSS_MOTOR' as MilestoneDomain, title: 'Head Turns Side to Side', description: 'During tummy time, your baby can briefly turn their head from one side to the other.', status: 'EXPECTED' as MilestoneStatus, activityPrompt: 'During tummy time, place a mirror or your face on alternating sides to encourage head turning.', xpReward: 15 },
    { stageKey: 'born_week_2', domain: 'LANGUAGE_COMMUNICATION' as MilestoneDomain, title: 'Prefers Human Speech', description: 'Your newborn shows a preference for human speech over other sounds and may quiet to familiar voices.', status: 'EXPECTED' as MilestoneStatus, activityPrompt: 'Talk, read, or sing to your baby during awake windows — your voice is their favorite sound.', xpReward: 15 },
    { stageKey: 'born_week_4', domain: 'FINE_MOTOR' as MilestoneDomain, title: 'Hands Begin to Open', description: 'The tight newborn fist begins to relax, and hands spend more time open and exploring.', status: 'EXPECTED' as MilestoneStatus, activityPrompt: 'Place a soft rattle or your finger in your baby\'s open palm during calm moments.', xpReward: 15 },
    { stageKey: 'born_week_4', domain: 'SOCIAL_EMOTIONAL' as MilestoneDomain, title: 'First Brief Social Engagement', description: 'Your baby may hold eye contact for a few seconds and show quiet alert states when engaged.', status: 'EXPECTED' as MilestoneStatus, activityPrompt: 'Hold your baby 8-12 inches from your face and make slow, exaggerated expressions.', xpReward: 15 },
    { stageKey: 'born_week_8', domain: 'COGNITIVE' as MilestoneDomain, title: 'Recognizes Primary Caregivers', description: 'Your baby shows recognition of familiar caregivers through calming, gazing, and turning toward voices.', status: 'EXPECTED' as MilestoneStatus, activityPrompt: 'When your baby looks at you, smile and speak warmly — you are their favorite person.', xpReward: 15 },
    { stageKey: 'born_week_10', domain: 'FINE_MOTOR' as MilestoneDomain, title: 'Brings Hands to Midline', description: 'Your baby begins to bring both hands together at the center of the body, a key coordination milestone.', status: 'EXPECTED' as MilestoneStatus, activityPrompt: 'Hang a lightweight toy at chest level during back play to encourage midline reaching.', xpReward: 15 },
    { stageKey: 'born_week_10', domain: 'LANGUAGE_COMMUNICATION' as MilestoneDomain, title: 'Vocalizes in Response to Speech', description: 'Your baby coos and makes sounds in response to being spoken to — the earliest conversation.', status: 'EXPECTED' as MilestoneStatus, activityPrompt: 'Talk to your baby, then pause and wait — they may vocalize back in turn-taking fashion.', xpReward: 15 },
    // ─── Infant months: bridging gaps ───
    { stageKey: 'born_month_3', domain: 'LANGUAGE_COMMUNICATION' as MilestoneDomain, title: 'Laughs Aloud', description: 'Your baby produces full belly laughs in response to playful interaction and physical stimulation.', status: 'EXPECTED' as MilestoneStatus, activityPrompt: 'Try raspberries on the tummy, peekaboo, or silly faces to discover what makes your baby laugh.', xpReward: 15 },
    { stageKey: 'born_month_4', domain: 'COGNITIVE' as MilestoneDomain, title: 'Explores Objects with Mouth', description: 'Your baby brings objects to their mouth to explore texture, shape, and temperature — a primary learning mode.', status: 'EXPECTED' as MilestoneStatus, activityPrompt: 'Offer safe, clean textured teethers and toys for oral exploration during supervised play.', xpReward: 15 },
    { stageKey: 'born_month_5', domain: 'LANGUAGE_COMMUNICATION' as MilestoneDomain, title: 'Takes Turns Vocalizing', description: 'Your baby engages in vocal turn-taking — cooing, waiting for your response, then cooing again.', status: 'EXPECTED' as MilestoneStatus, activityPrompt: 'Create a conversation: make a sound, wait for your baby to respond, then respond back.', xpReward: 15 },
    { stageKey: 'born_month_6', domain: 'FINE_MOTOR' as MilestoneDomain, title: 'Raking Grasp Emerges', description: 'Your baby uses a raking motion with all fingers to scoop small objects toward themselves.', status: 'EXPECTED' as MilestoneStatus, activityPrompt: 'Place baby-safe finger foods on the tray and watch the raking motion in action.', xpReward: 15 },
    { stageKey: 'born_month_7', domain: 'SOCIAL_EMOTIONAL' as MilestoneDomain, title: 'Enjoys Social Play Routines', description: 'Your baby anticipates and delights in repetitive social games like peekaboo and pat-a-cake.', status: 'EXPECTED' as MilestoneStatus, activityPrompt: 'Play the same game several times — pause before the climax and watch your baby anticipate.', xpReward: 15 },
    { stageKey: 'born_month_8', domain: 'LANGUAGE_COMMUNICATION' as MilestoneDomain, title: 'Understands "No" Briefly', description: 'Your baby pauses briefly in response to a firm "no," showing early receptive understanding.', status: 'EXPECTED' as MilestoneStatus, activityPrompt: 'Use "no" sparingly for safety situations only, and immediately redirect to an acceptable alternative.', xpReward: 15 },
    { stageKey: 'born_month_9', domain: 'COGNITIVE' as MilestoneDomain, title: 'Looks for Hidden Objects', description: 'Your baby will search briefly for a toy you hide under a cloth — the emergence of object permanence.', status: 'EXPECTED' as MilestoneStatus, activityPrompt: 'Hide a favorite toy partially under a blanket and ask "Where did it go?" — celebrate when found.', xpReward: 15 },
    { stageKey: 'born_month_10', domain: 'FINE_MOTOR' as MilestoneDomain, title: 'Pincer Grasp Refining', description: 'The pincer grasp — picking up objects between thumb and forefinger — becomes more precise.', status: 'EXPECTED' as MilestoneStatus, activityPrompt: 'Offer small, safe finger foods like puffs or soft pea-sized vegetables for pincer practice.', xpReward: 15 },
    { stageKey: 'born_month_11', domain: 'SOCIAL_EMOTIONAL' as MilestoneDomain, title: 'Shows Stranger Anxiety Clearly', description: 'Your baby clearly differentiates familiar from unfamiliar people, showing wariness with strangers.', status: 'EXPECTED' as MilestoneStatus, activityPrompt: 'Hold your baby when meeting new people and let them warm up at their own pace.', xpReward: 15 },
    { stageKey: 'born_month_12', domain: 'COGNITIVE' as MilestoneDomain, title: 'Uses Objects Correctly', description: 'Your baby uses everyday objects for their intended purpose — brushing hair, drinking from cup, babbling into phone.', status: 'EXPECTED' as MilestoneStatus, activityPrompt: 'Provide safe versions of everyday objects — a toy phone, a brush, a cup — and model their use.', xpReward: 15 },
    // ─── Toddler months: key milestone gaps ───
    { stageKey: 'born_month_14', domain: 'LANGUAGE_COMMUNICATION' as MilestoneDomain, title: 'Uses 3-5 Words Consistently', description: 'Your toddler consistently uses a handful of words with clear meaning — a joy to witness.', status: 'EXPECTED' as MilestoneStatus, activityPrompt: 'Respond enthusiastically to every word attempt and expand: "Ball! Yes, the red ball is rolling."', xpReward: 15 },
    { stageKey: 'born_month_16', domain: 'FINE_MOTOR' as MilestoneDomain, title: 'Scribbles Spontaneously', description: 'Your toddler makes purposeful marks on paper with a crayon — the joyful beginning of drawing and writing.', status: 'EXPECTED' as MilestoneStatus, activityPrompt: 'Tape large paper to the floor or table, offer chunky crayons, and celebrate every mark.', xpReward: 15 },
    { stageKey: 'born_month_18', domain: 'SOCIAL_EMOTIONAL' as MilestoneDomain, title: 'Shows Affection to Familiar People', description: 'Your toddler spontaneously shows affection through hugs, kisses, or offering comfort items.', status: 'EXPECTED' as MilestoneStatus, activityPrompt: 'Model affection warmly and accept your toddler\'s offers with gratitude — "Thank you for the hug!"', xpReward: 15 },
    { stageKey: 'born_month_20', domain: 'COGNITIVE' as MilestoneDomain, title: 'Completes Simple Puzzles', description: 'Your toddler can place 2-3 pieces into a simple wooden puzzle or shape sorter with focus.', status: 'EXPECTED' as MilestoneStatus, activityPrompt: 'Start with single-piece puzzles and gradually add complexity as your toddler masters each stage.', xpReward: 15 },
    { stageKey: 'born_month_22', domain: 'LANGUAGE_COMMUNICATION' as MilestoneDomain, title: 'Uses 50+ Words and Simple Sentences', description: 'Your toddler\'s vocabulary has grown to 50+ words and they regularly combine 2-3 words into sentences.', status: 'EXPECTED' as MilestoneStatus, activityPrompt: 'Expand on their sentences: "More milk? Let\'s get you more milk in your blue cup."', xpReward: 15 },
    { stageKey: 'born_month_24', domain: 'FINE_MOTOR' as MilestoneDomain, title: 'Turns Pages One at a Time', description: 'Your toddler can turn board book pages individually, a key fine motor and book-handling skill.', status: 'EXPECTED' as MilestoneStatus, activityPrompt: 'Let your toddler turn the pages during story time — it builds book skills and autonomy.', xpReward: 15 },
    { stageKey: 'born_month_24', domain: 'SOCIAL_EMOTIONAL' as MilestoneDomain, title: 'Plays Alongside Other Children', description: 'Your toddler engages in parallel play — playing near peers and occasionally imitating their actions.', status: 'EXPECTED' as MilestoneStatus, activityPrompt: 'Arrange short, supervised playdates with 1-2 other toddlers and provide duplicate toys.', xpReward: 15 },
  ];
  for (const m of milestones) {
    await prisma.milestoneExpectation.upsert({
      where: { id: `seed_milestone_${m.stageKey}_${m.domain}_${m.title.replace(/[^a-zA-Z0-9]/g, '_').substring(0, 30)}` },
      update: m, create: { id: `seed_milestone_${m.stageKey}_${m.domain}_${m.title.replace(/[^a-zA-Z0-9]/g, '_').substring(0, 30)}`, ...m },
    });
  }
  console.log(`Seeded ${milestones.length} additional milestone expectations`);
}
