import { PrismaClient, AdviceCategory, ContentSource } from '@prisma/client';

const prisma = new PrismaClient();

/**
 * Batch 5 — Fill remaining thin stages to minimum 5 cards per stage.
 * Targets: toddler months 13-24 (add 3 each), newborn weeks 2-6 (fill to 5),
 * and thin pregnancy weeks (fill to 5).
 */

// ── Toddler months 13-24: add PARENT_WELLBEING and PLAY_ACTIVITIES cards ──
const toddlerCards: Array<{
  stageKey: string;
  category: AdviceCategory;
  priority: number;
  title: string;
  summary: string;
  content: string;
  source: ContentSource;
  tags: string[];
}> = [];

// Helper to add a card for every toddler month
function addToddlerCard(
  stageKey: string,
  category: AdviceCategory,
  priority: number,
  title: string,
  summary: string,
  content: string,
  source: ContentSource,
  tags: string[],
) {
  toddlerCards.push({ stageKey, category, priority, title, summary, content, source, tags });
}

// ── Toddler Parent Wellbeing (1 per month, months 13-24) ──
const toddlerParentWellbeing = [
  { month: 13, title: 'Finding Your Rhythm as a Toddler Parent', summary: 'You have survived the first year. Now the toddler era brings its own rhythm.', content: 'The toddler phase is physically demanding but emotionally rewarding. Your child is walking, exploring, and beginning to communicate. This is a good time to revisit your self-care routines. Even 15 minutes of uninterrupted quiet time can reset your patience. Consider joining a local playgroup — not just for your toddler\'s social skills, but for the adult conversation and community support. Many parents find this stage easier than the newborn phase because sleep is more predictable and communication is two-way.' },
  { month: 14, title: 'Managing Toddler Mealtime Stress', summary: 'Picky eating peaks around 14 months. You are not failing as a parent.', content: 'Food refusal is a normal developmental phase, not a reflection of your cooking or parenting. Toddlers have small stomachs and erratic appetites. Offer a variety of healthy options without pressure. The division of responsibility approach works well: you decide what and when, your toddler decides whether and how much. Keep mealtimes short and positive. If you are feeling frustrated, step away and remember that growth is measured over weeks, not individual meals. Many toddlers go through phases of eating only one color or texture — this typically resolves by age 2.' },
  { month: 15, title: 'The Mental Load of Tracking Everything', summary: 'You have been logging milestones, feeds, and sleep for over a year. That is a lot of data.', content: 'Tracking your baby\'s development is valuable, but it can also create anxiety. If you find yourself obsessing over growth percentiles or comparing your toddler to others, consider reducing tracking frequency. Log only what feels meaningful. Your pediatrician is the ultimate authority on whether development is on track. The BabyMon app is a tool, not a judge. Many parents benefit from reducing to milestone-only tracking after the first birthday while continuing to enjoy the memory features like the photo album.' },
  { month: 16, title: 'Reconnecting With Your Partner During the Toddler Phase', summary: 'The toddler phase can strain relationships as parenting demands remain high.', content: 'By 16 months, many couples have not had a proper date night in over a year. The constant demands of toddler care leave little energy for adult connection. This is normal but addressable. Start small: a 10-minute daily check-in after the toddler is asleep, with no phones and no parenting topics. Schedule regular couple time, even if it is just a coffee during nap time. Remember that a strong co-parenting relationship benefits your child as much as it benefits you. If you are co-parenting across households, clear communication about routines and expectations becomes even more important.' },
  { month: 17, title: 'When Your Toddler Prefers One Parent', summary: 'Parental preference is a normal phase. It is not a rejection of you.', content: 'Around 17 months, many toddlers develop a strong preference for one parent, often the primary caregiver. This can be hurtful for the less-preferred parent. Understand that this is about comfort and familiarity, not love. The preferred parent should encourage the other parent to take over enjoyable activities like bath time or playground trips. Consistency from both parents builds security. This phase typically passes within a few months as your toddler\'s social awareness expands. Both parents remain equally important in your child\'s development.' },
  { month: 18, title: 'Returning to Work or Adjusting Roles', summary: 'The 18-month mark often coincides with major childcare transitions.', content: 'Many parents return to work or change childcare arrangements around 18 months. Separation anxiety may resurface during this transition. Prepare your toddler with short practice separations and a consistent goodbye ritual. Trust that your child is resilient and that quality time matters more than quantity. If you are staying home, you may feel isolated as peers return to work. Both choices are valid. The toddler years are an excellent time to reassess your work-life balance and make adjustments that serve your family\'s needs.' },
  { month: 19, title: 'Dealing With Unsolicited Parenting Advice', summary: 'By 19 months, you have probably heard every piece of advice there is.', content: 'Strangers, relatives, and social media all have opinions about your parenting. Learn to filter. Evidence-based sources like your pediatrician and AAP guidelines are trustworthy. Well-meaning relatives may push outdated practices — you can acknowledge their experience while following current recommendations. Develop a polite deflection: "Thanks, we are following our pediatrician\'s guidance on that." Your confidence as a parent grows when you trust your own judgment. You know your child better than anyone else.' },
  { month: 20, title: 'Toddler-Proofing Your Home: Beyond Baby Gates', summary: 'Twenty-month-olds are creative explorers. Safety needs evolve.', content: 'As your toddler gains new physical abilities, safety risks change. Secure furniture to walls as climbing begins. Move cleaning supplies to high cabinets or locked storage. Check window blind cords, electrical outlets, and any small objects that could become choking hazards. The bathroom is especially dangerous — install toilet locks and never leave standing water. Take a toddler\'s-eye view by crawling around each room. This is also a good time to review your first aid knowledge and ensure emergency numbers are easily accessible.' },
  { month: 21, title: 'Screen Time Decisions for Toddlers', summary: 'Your toddler is increasingly interested in screens. Set boundaries early.', content: 'AAP guidelines recommend limiting screen time for children under 2 to video calls only. At 21 months, your toddler may be drawn to screens. If you choose to introduce limited screen time, prioritize interactive content over passive watching. Watch together and narrate what you see. Avoid screens during meals and the hour before bedtime. Remember that unstructured play, outdoor time, and face-to-face interaction remain the most important developmental activities. There is no educational screen content proven to accelerate toddler development more than real-world exploration.' },
  { month: 22, title: 'Preparing for the "Terrible Twos" — Spoiler: It Is Not Terrible', summary: 'The approach to age two brings big emotions. This is normal development.', content: 'The so-called terrible twos are actually a period of rapid brain development. Your toddler is learning independence, language, and emotional regulation simultaneously — an enormous cognitive load. Tantrums are not misbehavior; they are communication from an overwhelmed nervous system. Stay calm, offer comfort, and help name emotions. After the storm passes, reconnect with a hug or favorite activity. This phase builds emotional intelligence and resilience. Parents who respond with patience rather than punishment raise children with better emotional regulation skills.' },
  { month: 23, title: 'Celebrating Your Parenting Journey: Almost Two Years', summary: 'You have nearly two years of parenting experience. That is worth celebrating.', content: 'As you approach your child\'s second birthday, take stock of everything you have learned. You have navigated pregnancy or adoption, newborn sleeplessness, feeding challenges, first steps, first words, and countless doctor visits. You have become an expert on your specific child. Many parents find it meaningful to write a letter to themselves or their child at this milestone, reflecting on the journey. Consider creating a photo book from your BabyMon album. These years are intense but fleeting — you are doing remarkable work.' },
  { month: 24, title: 'Graduation: Your Baby Is Now a Two-Year-Old', summary: 'Congratulations. You have completed the BabyMon journey from conception to age two.', content: 'Your child has transformed from a newborn into a walking, talking, opinionated little person. This is a major milestone for both of you. BabyMon can archive this profile as a keepsake of your tracking journey. Export your data for your pediatrician or your own records. The parenting journey continues — you are now entering the preschool years with two years of hard-won experience. Take pride in everything you have accomplished. Your child is healthy, curious, and loved, and that is because of you.' },
];

for (const c of toddlerParentWellbeing) {
  addToddlerCard(
    `born_month_${c.month}`,
    'PARENT_WELLBEING',
    90,
    c.title,
    c.summary,
    c.content,
    'GENERAL',
    ['parent wellbeing', 'self care', 'toddler parenting', 'mental health'],
  );
}

// ── Toddler Play & Activities (1 per month, months 13-24) ──
const toddlerPlayActivities = [
  { month: 13, title: 'Water Play for Early Toddlers', summary: 'Simple water play develops fine motor skills and sensory awareness.', content: 'Fill a shallow basin with warm water and provide cups, spoons, and floating toys. Supervise closely at all times. Pouring, scooping, and splashing build hand strength and coordination. Add a few drops of food coloring for visual interest. This activity can easily occupy a 13-month-old for 20 minutes. Water play also introduces early science concepts like volume and cause-effect. Keep towels handy and embrace the mess — sensory play is how toddlers learn about their world.' },
  { month: 14, title: 'Push and Pull Toys for Walking Confidence', summary: 'Push toys help new walkers build balance and coordination.', content: 'At 14 months, your toddler is likely walking or about to start. Push toys like small shopping carts or animal walkers provide stability and motivation. Pull toys on strings introduce cause-effect and spatial awareness. Choose sturdy toys with wide bases that will not tip easily. Avoid walkers with seats, which can delay walking and pose safety risks. Follow your toddler\'s lead — some prefer to push, others to pull. Both activities strengthen leg muscles and build confidence for independent walking.' },
  { month: 15, title: 'Simple Sorting Games for Cognitive Development', summary: 'Sorting by color, shape, or size builds early math and logic skills.', content: 'Collect household items in two or three categories: red and blue blocks, big and small spoons, soft and hard toys. Show your toddler how to sort one item, then let them try. Celebrate every attempt regardless of accuracy. Sorting builds categorization skills that form the foundation for later math learning. Keep sessions short — five minutes is plenty for a 15-month-old attention span. Praise effort over correctness. As skills develop, add a third category or introduce more subtle distinctions.' },
  { month: 16, title: 'Music and Movement for Language Development', summary: 'Singing and dancing together boosts vocabulary and motor coordination.', content: 'Simple action songs like "Head Shoulders Knees and Toes" or "The Wheels on the Bus" combine language, music, and movement. Your 16-month-old may not sing the words yet but will attempt the motions. Dancing together develops rhythm, balance, and social bonding. Make instruments from household items — a pot and wooden spoon make a satisfying drum. Music activates multiple brain regions simultaneously, supporting both language and motor development. Turn on music during transitions to signal activity changes.' },
  { month: 17, title: 'Texture Exploration Bins', summary: 'A sensory bin filled with safe textures provides hours of focused play.', content: 'Fill a shallow container with dry rice, pasta, or oats. Add scoops, small containers, and hidden toys. Your 17-month-old will pour, scoop, and search with intense concentration. This builds fine motor skills and sensory processing. Always supervise closely to prevent mouthing. Rotate materials weekly to maintain interest. Start with larger items like dry pasta and progress to finer textures as your toddler learns not to mouth them. This activity also builds vocabulary as you describe textures together: rough, smooth, bumpy, soft.' },
  { month: 18, title: 'Simple Puzzles for Problem-Solving', summary: 'Wooden peg puzzles with 3-5 pieces are perfect for 18-month-olds.', content: 'Choose puzzles with large knobs and familiar themes like animals or vehicles. Demonstrate how to remove and replace one piece, then let your toddler try. Matching shapes to spaces develops spatial reasoning and persistence. Do not correct mistakes immediately — let your toddler discover the fit. Puzzle play also builds hand-eye coordination and the pincer grip needed for writing later. Rotate puzzles to maintain novelty. Celebrate completion with clapping and specific praise: "You found where the cow goes!"' },
  { month: 19, title: 'Outdoor Nature Walks for Curious Toddlers', summary: 'A simple walk becomes an adventure when you follow your toddler\'s pace.', content: 'At 19 months, your toddler notices everything: leaves, bugs, puddles, clouds. Let them lead. Stop to examine interesting finds. Name objects you see and describe their properties. Collect safe natural items like pinecones or smooth stones in a small basket. Nature walks build vocabulary, observation skills, and a connection to the outdoors. Keep walks short and flexible — the destination matters less than the exploration. Regular outdoor time also supports healthy sleep patterns and reduces toddler stress.' },
  { month: 20, title: 'Pretend Play with Simple Props', summary: 'A cardboard box and a few props spark imaginative play at 20 months.', content: 'Pretend play emerges strongly around 20 months. Provide simple props: a toy phone, a doll with a bottle, play food, or a cardboard box that becomes a car or house. Join the play as a participant, not a director. Follow your toddler\'s imagination rather than correcting it. Pretend play builds language, social skills, and emotional understanding. It also gives you a window into your toddler\'s inner world. Keep props simple — the best toy is often an ordinary household object your toddler has claimed as something magical.' },
  { month: 21, title: 'Building Towers and Knocking Them Down', summary: 'Block play teaches physics, persistence, and cause-effect in the most fun way.', content: 'At 21 months, your toddler can stack 4-6 blocks. Building and knocking down towers is endlessly entertaining and developmentally valuable. Use large, lightweight blocks that are easy to grip. Celebrate tall towers and dramatic crashes equally. Block play builds fine motor control, spatial reasoning, and understanding of balance. Narrate the play: "You put the red block on top. Uh oh, it fell down. Let us try again." This simple activity contains lessons in physics, engineering, and emotional resilience.' },
  { month: 22, title: 'Finger Painting for Creative Expression', summary: 'Messy, colorful, and deeply satisfying — finger painting is pure creative joy.', content: 'Use washable, non-toxic finger paints on a large sheet of paper. Strip your toddler down to a diaper and embrace the mess. Let them explore color mixing, texture, and mark-making without direction. Finger painting builds fine motor skills, color recognition, and creative confidence. The process matters more than the product. Display the artwork on the refrigerator to show you value their creativity. Cleanup is part of the activity — provide a warm washcloth and narrate the transition from messy play to clean hands.' },
  { month: 23, title: 'Obstacle Courses for Gross Motor Skills', summary: 'A simple indoor obstacle course channels your toddler\'s endless energy productively.', content: 'Use couch cushions, pillows, and cardboard boxes to create a safe obstacle course. Include crawling under a table, stepping over pillows, and walking along a taped line on the floor. Time is not important — focus on effort and fun. Obstacle courses build coordination, balance, and spatial awareness. They also provide the vigorous physical activity toddlers need for healthy development and good sleep. Change the course weekly to maintain interest. Narrate the actions: "You are crawling under the tunnel. Now step over the pillow mountain."' },
  { month: 24, title: 'Celebration Art: Making a Birthday Crown', summary: 'Create a special crown together to celebrate your toddler turning two.', content: 'Cut a crown shape from construction paper. Provide stickers, washable markers, and glue sticks. Let your toddler decorate freely. This collaborative art project builds fine motor skills and creates a treasured keepsake. Talk about the birthday and how much they have grown. The crown can be worn during birthday celebrations and saved in a memory box. This activity marks the transition from babyhood to the preschool years and celebrates your child\'s incredible journey.' },
];

for (const c of toddlerPlayActivities) {
  addToddlerCard(
    `born_month_${c.month}`,
    'PLAY_ACTIVITIES',
    76,
    c.title,
    c.summary,
    c.content,
    'DEVELOPMENT',
    ['play', 'toddler activities', 'motor skills', 'sensory play'],
  );
}

// ── Thin newborn weeks: fill born_week_2,3,4,6 to 5+ cards ──
const newbornFillCards: Array<{
  stageKey: string;
  category: AdviceCategory;
  priority: number;
  title: string;
  summary: string;
  content: string;
  source: ContentSource;
  tags: string[];
}> = [
  // born_week_2 — needs SLEEP, NUTRITION_FEEDING, PLAY_ACTIVITIES
  { stageKey: 'born_week_2', category: 'SLEEP', priority: 95, title: 'Safe Sleep Guidelines for Week 2', summary: 'Your newborn sleeps 14-17 hours daily. Safe sleep practices are essential.', content: 'Always place your baby on their back to sleep, on a firm mattress with a fitted sheet only. No blankets, pillows, bumpers, or stuffed animals in the crib. Room-sharing without bed-sharing is recommended for the first 6-12 months. Your baby may seem to sleep restlessly — newborns spend much of their sleep in active REM sleep, which is normal and supports brain development. If your baby falls asleep in a car seat or swing, transfer them to a safe sleep surface as soon as possible.', source: 'CLINICAL', tags: ['safe sleep', 'SIDS prevention', 'newborn sleep', 'sleep safety'] },
  { stageKey: 'born_week_2', category: 'NUTRITION_FEEDING', priority: 95, title: 'Cluster Feeding at Two Weeks', summary: 'Frequent feeding is normal and helps establish your milk supply.', content: 'At two weeks, many newborns enter a cluster feeding phase, nursing every 45-90 minutes for several hours, often in the evening. This is not a sign of low milk supply — it is your baby helping to increase your production to meet growing demands. Let your baby feed on demand. If formula feeding, your baby may take 2-3 ounces every 2-3 hours. Watch for hunger cues like rooting, hand-sucking, and lip-smacking. Crying is a late hunger sign. Track feeds in BabyMon to see patterns emerge over time.', source: 'CLINICAL', tags: ['cluster feeding', 'newborn nutrition', 'breastfeeding', 'formula feeding'] },
  { stageKey: 'born_week_2', category: 'PLAY_ACTIVITIES', priority: 80, title: 'Your Baby\'s First Social Smiles', summary: 'Around two weeks, your baby may begin showing reflex smiles during sleep.', content: 'While true social smiles typically emerge around 6-8 weeks, you may notice reflex smiles during active sleep. These are involuntary but delightful. Hold your baby 8-12 inches from your face — newborns see best at this distance. Make eye contact and speak in a soft, high-pitched voice. Your baby is learning that faces are interesting and that social interaction is rewarding. These early bonding moments build the foundation for attachment and later social development.', source: 'DEVELOPMENT', tags: ['newborn smiles', 'social development', 'bonding', 'eye contact'] },

  // born_week_3 — needs SLEEP, NUTRITION_FEEDING, PLAY_ACTIVITIES, PARENT_WELLBEING
  { stageKey: 'born_week_3', category: 'SLEEP', priority: 95, title: 'Understanding Newborn Sleep Cycles at Week 3', summary: 'Your baby\'s sleep cycles are about 50-60 minutes — much shorter than adult cycles.', content: 'Newborns spend about half their sleep in active REM sleep, which is lighter and more easily disrupted. They transition between sleep cycles frequently and may wake briefly. This is normal and protective — lighter sleep is associated with lower SIDS risk. Help your baby learn day-night distinction by keeping daytime feeds in bright rooms and nighttime feeds dark and quiet. Swaddling can help contain the startle reflex that often wakes newborns. Sleep patterns will begin to consolidate around 6-8 weeks.', source: 'CLINICAL', tags: ['newborn sleep', 'sleep cycles', 'REM sleep', 'day-night rhythm'] },
  { stageKey: 'born_week_3', category: 'NUTRITION_FEEDING', priority: 95, title: 'Growth Spurt at Three Weeks', summary: 'The three-week growth spurt brings increased hunger and fussiness. This is temporary.', content: 'Around 3 weeks, many babies have their first major growth spurt, nursing more frequently and seeming never satisfied. This typically lasts 2-3 days. Your body will respond by increasing milk production. If formula feeding, you may need to increase volume slightly. Signs of adequate intake include 6-8 wet diapers daily, regular bowel movements, and weight gain at pediatrician visits. Do not be alarmed if your baby seems hungrier than last week — they are growing rapidly and the increased demand drives increased supply.', source: 'CLINICAL', tags: ['growth spurt', 'newborn feeding', 'milk supply', 'hunger cues'] },
  { stageKey: 'born_week_3', category: 'PLAY_ACTIVITIES', priority: 80, title: 'Tummy Time at Three Weeks', summary: 'Short, frequent tummy time sessions build neck and shoulder strength.', content: 'Start with 1-2 minutes of tummy time, 2-3 times per day, on a firm, safe surface. Get down on the floor at eye level and talk or sing to encourage your baby to lift their head. Never leave your baby unsupervised during tummy time. Some babies dislike tummy time initially — try placing them on your chest while you recline. This provides the same muscle-building benefits with the comfort of your heartbeat and warmth. Gradually increase duration as your baby builds strength and tolerance.', source: 'DEVELOPMENT', tags: ['tummy time', 'motor development', 'neck strength', 'newborn exercises'] },
  { stageKey: 'born_week_3', category: 'PARENT_WELLBEING', priority: 85, title: 'Postpartum Recovery at Three Weeks', summary: 'You are still healing. Give yourself the same patience you give your baby.', content: 'At three weeks postpartum, your body is still recovering from birth. Bleeding may continue (lochia). Cesarean incision or perineal tears are healing. Rest as much as possible. Accept help with meals, laundry, and other household tasks. If you had a vaginal delivery, wait until your provider clears you before resuming exercise or sexual activity. Watch for signs of postpartum depression: persistent sadness, loss of interest, difficulty bonding, or thoughts of harming yourself or your baby. These are medical conditions, not personal failings. Contact your provider immediately if you experience these symptoms.', source: 'GENERAL', tags: ['postpartum recovery', 'maternal health', 'healing', 'postpartum depression'] },

  // born_week_4 — needs PARENT_WELLBEING, PLAY_ACTIVITIES, SLEEP
  { stageKey: 'born_week_4', category: 'PARENT_WELLBEING', priority: 85, title: 'The Fourth Trimester: Understanding Your Newborn\'s Needs', summary: 'Your baby still thinks they are part of you. The fourth trimester concept explains why.', content: 'The first three months after birth are sometimes called the fourth trimester. Your newborn is adjusting to life outside the womb and craves the warmth, motion, and constant contact they experienced before birth. Holding, wearing, rocking, and feeding on demand are not spoiling your baby — they are meeting genuine developmental needs. Understanding this can reduce frustration when your baby seems inconsolable. This phase is temporary. By 12 weeks, your baby will begin to develop self-soothing skills and longer alert periods.', source: 'DEVELOPMENT', tags: ['fourth trimester', 'newborn needs', 'attachment', 'holding'] },
  { stageKey: 'born_week_4', category: 'PLAY_ACTIVITIES', priority: 80, title: 'High-Contrast Visual Stimulation', summary: 'Black and white patterns captivate your four-week-old\'s developing vision.', content: 'Your newborn sees high-contrast patterns best at this age. Create simple black and white cards with bold stripes, checkerboards, or simple faces. Hold them 8-12 inches from your baby\'s face during alert periods. You may notice your baby staring intently at ceiling fans, window blinds, or other high-contrast edges — these are natural visual stimulants. Books with black and white illustrations are excellent investments. Visual tracking will improve dramatically over the next few weeks as your baby\'s visual cortex develops.', source: 'DEVELOPMENT', tags: ['visual development', 'high contrast', 'newborn vision', 'brain development'] },
  { stageKey: 'born_week_4', category: 'SLEEP', priority: 95, title: 'When Will My Baby Sleep Through the Night?', summary: 'The honest answer is not yet. But you can start building healthy habits now.', content: 'At four weeks, your baby is not developmentally ready to sleep through the night. Their stomach is tiny, and they need frequent feeds. Most newborns wake every 2-4 hours. However, you can begin establishing a simple bedtime routine: a warm bath, gentle massage, feeding, and a lullaby. Keep nighttime interactions minimal and businesslike — quiet voice, dim lights, no play. This helps your baby learn that nighttime is for sleeping. True sleep consolidation typically begins between 3-6 months. This phase, while exhausting, is temporary.', source: 'CLINICAL', tags: ['newborn sleep', 'sleep through night', 'bedtime routine', 'sleep expectations'] },

  // born_week_6 — needs PARENT_WELLBEING, NUTRITION_FEEDING, PLAY_ACTIVITIES
  { stageKey: 'born_week_6', category: 'PARENT_WELLBEING', priority: 85, title: 'The Six-Week Checkup and Your Recovery', summary: 'Your postpartum checkup is an important milestone for your health.', content: 'The six-week postpartum visit is typically when your provider clears you for exercise, sexual activity, and return to work planning. Prepare questions in advance: discuss contraception, pelvic floor recovery, emotional health, and any lingering pain or discomfort. Be honest about how you are feeling. Many parents experience anxiety about resuming normal activities — this is common. If you experienced birth trauma, ask about pelvic floor physical therapy. Your health matters as much as your baby\'s. You cannot pour from an empty cup.', source: 'GENERAL', tags: ['postpartum checkup', 'maternal health', 'recovery', 'six weeks'] },
  { stageKey: 'born_week_6', category: 'NUTRITION_FEEDING', priority: 92, title: 'Recognizing Hunger and Fullness Cues at Six Weeks', summary: 'Your baby is becoming a more efficient feeder. Learn their unique signals.', content: 'By six weeks, you and your baby are developing a feeding rhythm. Early hunger cues include rooting, hand-sucking, and increased alertness. Crying is a late cue — try to feed before crying begins for a calmer feeding experience. Fullness cues include releasing the nipple, turning away, relaxed hands, and drowsiness. Your baby knows when they are full — trust their signals rather than pushing for a specific volume. If breastfeeding, you may notice your breasts feel softer as your supply regulates. This is normal and does not indicate low supply.', source: 'CLINICAL', tags: ['hunger cues', 'fullness cues', 'feeding rhythm', 'responsive feeding'] },
  { stageKey: 'born_week_6', category: 'PLAY_ACTIVITIES', priority: 80, title: 'The First Real Smile: Social Play Begins', summary: 'Around six weeks, your baby rewards you with their first genuine social smile.', content: 'The social smile is a major developmental milestone. Unlike reflex smiles, this is your baby intentionally engaging with you. Respond with exaggerated smiles, gentle laughter, and happy talk. This back-and-forth is the foundation of communication and social development. Spend time face-to-face during alert periods. Your baby may also begin cooing around this time — simple vowel sounds like "oo" and "ah." Talk back as if having a conversation, pausing to let them respond. These early interactions build the neural pathways for language and emotional connection.', source: 'DEVELOPMENT', tags: ['social smile', 'communication', 'cooing', 'social development'] },
];

// ── Thin pregnancy weeks: fill weeks 11, 17, 23, 25, 27, 28, 29, 31, 35, 39, 40 ──
const pregnancyFillCards: Array<{
  stageKey: string;
  category: AdviceCategory;
  priority: number;
  title: string;
  summary: string;
  content: string;
  source: ContentSource;
  tags: string[];
}> = [
  { stageKey: 'preg_week_11', category: 'PLAY_ACTIVITIES', priority: 80, title: 'Prenatal Bonding Activities for Week 11', summary: 'Even though you cannot feel kicks yet, bonding with your baby begins now.', content: 'Talk or sing to your growing belly. Your baby can hear muffled sounds by week 11 and will recognize your voice after birth. Start a pregnancy journal recording your thoughts and hopes. Take weekly belly photos to document your changing body. These rituals strengthen your emotional connection and become treasured keepsakes. Partners can participate by reading aloud or placing a hand on your belly. The sound of both parents\' voices contributes to newborn recognition and comfort after birth.', source: 'DEVELOPMENT', tags: ['prenatal bonding', 'baby communication', 'pregnancy journal', 'voice recognition'] },
  { stageKey: 'preg_week_11', category: 'SLEEP', priority: 90, title: 'Managing Pregnancy Fatigue in the First Trimester', summary: 'Extreme fatigue is normal. Your body is building a placenta and a human.', content: 'First trimester fatigue can be overwhelming. Your body is producing more blood, building the placenta, and supporting rapid embryonic development. Rest when you can — short naps and early bedtimes. Reduce non-essential commitments. If you work, consider asking for flexible hours or remote work options. Iron levels will be checked at your next prenatal visit — low iron can worsen fatigue. Proper hydration and small, frequent meals help maintain energy. This fatigue typically improves in the second trimester as the placenta takes over hormone production.', source: 'CLINICAL', tags: ['pregnancy fatigue', 'first trimester', 'energy levels', 'rest'] },
  { stageKey: 'preg_week_11', category: 'PARENT_WELLBEING', priority: 85, title: 'Sharing Your Pregnancy News', summary: 'Deciding when and how to announce your pregnancy is a personal choice.', content: 'Many parents wait until after the first trimester (week 12-13) to share pregnancy news broadly, when miscarriage risk drops significantly. There is no right answer — share when you feel ready. Consider who needs to know first: your partner, close family, your employer. Some parents tell one trusted person early for support while waiting to make a wider announcement. Prepare for a range of reactions. Not everyone responds with uncomplicated joy, and that is about them, not about you or your baby. Your excitement is valid regardless of others\' responses.', source: 'GENERAL', tags: ['pregnancy announcement', 'sharing news', 'first trimester', 'emotional health'] },

  { stageKey: 'preg_week_17', category: 'PLAY_ACTIVITIES', priority: 80, title: 'Feeling Baby Move: Quickening at Week 17', summary: 'The first flutters are called quickening. They feel like bubbles or butterflies.', content: 'First-time parents typically feel movement between 16-22 weeks. These early sensations are subtle — like gas bubbles, popcorn popping, or butterfly wings. They will become stronger and more distinct over the coming weeks. Try lying still after a meal or in the evening when your baby is often most active. Partners may not feel movement from outside for several more weeks. Start noting when you feel movement — patterns will emerge. If you have not felt movement by 24 weeks, mention it to your provider, but earlier variability is normal.', source: 'DEVELOPMENT', tags: ['quickening', 'baby movement', 'fetal activity', 'pregnancy sensations'] },
  { stageKey: 'preg_week_17', category: 'NUTRITION_FEEDING', priority: 90, title: 'Nutrition for the Second Trimester Surge', summary: 'Your baby\'s growth accelerates. Focus on nutrient-dense foods.', content: 'The second trimester brings increased caloric needs — about 300 extra calories daily. Prioritize protein (lean meats, eggs, legumes), calcium (dairy, fortified plant milks), iron (red meat, spinach, lentils), and omega-3 fatty acids (salmon, walnuts, chia seeds) for brain development. Continue prenatal vitamins. Stay hydrated — aim for 8-10 glasses of water daily. Food aversions from the first trimester often ease now. Listen to your body. Small, frequent meals help manage the increased appetite without discomfort.', source: 'CLINICAL', tags: ['pregnancy nutrition', 'second trimester', 'healthy eating', 'prenatal vitamins'] },
  { stageKey: 'preg_week_17', category: 'SLEEP', priority: 90, title: 'Sleep Position Changes in the Second Trimester', summary: 'Around 17 weeks, begin transitioning to side sleeping if you have not already.', content: 'Sleeping on your left side improves blood flow to the placenta and reduces pressure on major blood vessels. Avoid sleeping flat on your back for extended periods as your uterus grows. Use pillows to support your belly, back, and between your knees. A pregnancy pillow can be a worthwhile investment at this stage. If you wake on your back, simply roll to your side — do not stress about position changes during sleep. Good sleep positioning now prevents discomfort and circulatory issues later in pregnancy.', source: 'CLINICAL', tags: ['pregnancy sleep', 'sleep position', 'side sleeping', 'blood flow'] },

  { stageKey: 'preg_week_23', category: 'PLAY_ACTIVITIES', priority: 80, title: 'Your Baby Can Hear You Clearly Now', summary: 'By week 23, your baby\'s hearing is well developed. Read and sing to them.', content: 'Your baby responds to sounds outside the womb. Play music, read aloud, or have conversations with your belly. Your baby will recognize familiar voices and music after birth. Choose a special song or story to use now and continue after birth — the familiarity can soothe your newborn. Notice how your baby moves in response to loud noises or familiar voices. Partners should participate in this bonding activity. The sound of a parent\'s voice is one of the most comforting things for a newborn.', source: 'DEVELOPMENT', tags: ['fetal hearing', 'baby bonding', 'prenatal stimulation', 'voice recognition'] },
  { stageKey: 'preg_week_23', category: 'PARENT_WELLBEING', priority: 85, title: 'Body Image During Pregnancy', summary: 'Your body is changing rapidly. It is normal to have complex feelings.', content: 'Weight gain, stretch marks, and changing proportions can trigger body image concerns. Your body is performing an extraordinary biological task. Weight gain guidelines vary based on pre-pregnancy BMI — discuss with your provider. Focus on how your body feels and functions rather than how it looks. Surround yourself with positive messages about pregnancy bodies. If negative thoughts persist, discuss them with your provider or a therapist. Prenatal depression and anxiety can include body image distortion. You deserve support, not judgment.', source: 'GENERAL', tags: ['body image', 'pregnancy body', 'weight gain', 'emotional health'] },

  { stageKey: 'preg_week_25', category: 'SLEEP', priority: 90, title: 'Restless Legs and Pregnancy Insomnia', summary: 'Sleep disruption increases in the late second trimester. Several strategies can help.', content: 'Restless legs syndrome affects up to 26% of pregnant people. Iron and folate levels may contribute — discuss testing with your provider. Warm baths before bed, gentle leg stretches, and magnesium supplements (with provider approval) may help. Heartburn and frequent urination also disrupt sleep. Avoid eating within 2-3 hours of bedtime. Elevate your upper body with pillows. Reduce fluids in the evening while maintaining total daily hydration. If insomnia persists, cognitive behavioral therapy for insomnia (CBT-I) is safe and effective during pregnancy.', source: 'CLINICAL', tags: ['pregnancy sleep', 'restless legs', 'insomnia', 'sleep strategies'] },
  { stageKey: 'preg_week_25', category: 'NUTRITION_FEEDING', priority: 90, title: 'Glucose Screening: What to Expect at Week 24-28', summary: 'The glucose tolerance test screens for gestational diabetes.', content: 'Between 24-28 weeks, you will be offered a glucose screening test. You will drink a sweet liquid containing 50g of glucose, and your blood sugar will be tested one hour later. If results are elevated, a longer 3-hour test follows. Fasting overnight before the test may or may not be required — follow your provider\'s instructions. Gestational diabetes affects 6-9% of pregnancies and is manageable with diet, exercise, and sometimes medication. Early detection prevents complications for both you and your baby. Do not skip this screening.', source: 'CLINICAL', tags: ['glucose test', 'gestational diabetes', 'prenatal screening', 'blood sugar'] },

  { stageKey: 'preg_week_27', category: 'PARENT_WELLBEING', priority: 85, title: 'Entering the Third Trimester: What to Expect', summary: 'Welcome to the home stretch. The third trimester brings new changes.', content: 'The third trimester (weeks 27-40) brings increased fatigue, more frequent prenatal visits, and preparation for birth. Your baby is gaining weight rapidly, and you may feel it. Braxton Hicks contractions may begin — irregular, painless tightening that prepares your uterus for labor. Start thinking about your birth plan if you have not already. Take childbirth education classes. Pack your hospital bag around week 35. This trimester is about preparation, both practical and emotional. The finish line is approaching.', source: 'GENERAL', tags: ['third trimester', 'birth preparation', 'pregnancy timeline', 'Braxton Hicks'] },
  { stageKey: 'preg_week_27', category: 'SLEEP', priority: 90, title: 'Finding Comfortable Sleep Positions in Late Pregnancy', summary: 'As your belly grows, sleep requires more creativity and more pillows.', content: 'Left-side sleeping remains ideal. Use a full-length pregnancy pillow or arrange regular pillows: one under your belly, one behind your back, and one between your knees. A wedge pillow under your belly provides direct support. If heartburn wakes you, elevate your head and shoulders on multiple pillows or use a wedge. Shortness of breath when lying flat is common — sleeping semi-reclined can help. Accept that uninterrupted sleep is rare in late pregnancy. Short daytime rests compensate for nighttime disruptions.', source: 'CLINICAL', tags: ['pregnancy sleep', 'sleep positions', 'third trimester', 'comfort'] },

  { stageKey: 'preg_week_28', category: 'PLAY_ACTIVITIES', priority: 80, title: 'Kick Counting at Week 28', summary: 'Your provider may recommend tracking fetal movement daily.', content: 'Starting around week 28, monitor your baby\'s movement patterns. A common method: lie on your left side after a meal and count movements. Ten distinct movements within two hours is typical, though your baby has their own pattern. Choose a consistent time daily. Decreased movement can indicate fetal distress — contact your provider immediately if you notice a significant change, not tomorrow morning. Do not rely on home dopplers for reassurance. Your perception of movement is the most reliable indicator of fetal wellbeing.', source: 'CLINICAL', tags: ['kick counting', 'fetal movement', 'third trimester', 'baby wellbeing'] },
  { stageKey: 'preg_week_28', category: 'PARENT_WELLBEING', priority: 85, title: 'Preparing Siblings for the New Baby', summary: 'If you have older children, now is the time to begin preparation.', content: 'Read books about new siblings together. Involve older children in preparation: choosing baby clothes, setting up the nursery, picking a special gift from the baby to the sibling. Avoid major transitions (potty training, moving to a big bed) close to the due date. After birth, carve out one-on-one time with older children, even if just 10 minutes daily. Expect regression in behavior or sleep — this is normal and temporary. Your older child will adjust to their new role with patience and consistency.', source: 'GENERAL', tags: ['sibling preparation', 'older children', 'family dynamics', 'new baby'] },

  { stageKey: 'preg_week_29', category: 'NUTRITION_FEEDING', priority: 90, title: 'Third Trimester Nutrition: Fueling the Final Growth Spurt', summary: 'Your baby gains about half their birth weight in the third trimester.', content: 'Focus on quality nutrition. Continue prenatal vitamins. Iron needs peak in the third trimester — pair iron-rich foods with vitamin C for better absorption. Calcium supports your baby\'s bone development. Omega-3 fatty acids, particularly DHA, support brain development. Smaller, more frequent meals reduce heartburn and accommodate your compressed stomach. Stay hydrated to prevent Braxton Hicks contractions and reduce swelling. Avoid empty calories from sugary drinks and processed snacks. Every bite nourishes both you and your rapidly growing baby.', source: 'CLINICAL', tags: ['pregnancy nutrition', 'third trimester', 'iron', 'DHA'] },
  { stageKey: 'preg_week_29', category: 'SLEEP', priority: 90, title: 'Managing Pregnancy Heartburn at Night', summary: 'Heartburn peaks in the third trimester as your uterus presses on your stomach.', content: 'Eat smaller meals and avoid lying down for 2-3 hours after eating. Elevate your head with pillows or a wedge. Avoid trigger foods: spicy, acidic, fried, and fatty foods, chocolate, and caffeine. Antacids containing calcium carbonate are generally safe during pregnancy — confirm with your provider. If heartburn is severe, prescription medications may be appropriate. Do not suffer in silence. Effective treatment improves both your sleep quality and nutritional intake, benefiting both you and your baby.', source: 'CLINICAL', tags: ['pregnancy heartburn', 'acid reflux', 'sleep comfort', 'third trimester'] },

  { stageKey: 'preg_week_31', category: 'PLAY_ACTIVITIES', priority: 80, title: 'Responding to Your Baby\'s Hiccups', summary: 'Fetal hiccups are common and typically harmless. You may feel them daily.', content: 'Fetal hiccups feel like rhythmic, gentle tapping — different from kicks. They are caused by your baby\'s developing diaphragm and are usually a sign of a healthy nervous system. Some babies hiccup multiple times daily, others rarely. There is nothing you need to do in response. Hiccups will not harm your baby. If hiccups feel dramatically different from usual or are accompanied by decreased movement, contact your provider. Otherwise, enjoy this quirky reminder of the little person growing inside you.', source: 'DEVELOPMENT', tags: ['fetal hiccups', 'baby movement', 'third trimester', 'nervous system'] },
  { stageKey: 'preg_week_31', category: 'PARENT_WELLBEING', priority: 85, title: 'Childbirth Education: What to Look For', summary: 'Knowledge reduces fear. A good childbirth class prepares you for multiple scenarios.', content: 'Look for classes that cover: stages of labor, pain management options (both medicated and unmedicated), medical interventions and when they might be needed, cesarean birth, postpartum recovery, and newborn care basics. Both partners should attend if possible. Hospital tours help familiarize you with the environment. Consider your learning style — some prefer in-person, others online. Many hospitals offer free or low-cost classes. The goal is informed flexibility, not rigid adherence to a plan. Birth rarely follows a script.', source: 'GENERAL', tags: ['childbirth education', 'birth preparation', 'labor', 'parenting classes'] },

  { stageKey: 'preg_week_35', category: 'SLEEP', priority: 90, title: 'Final Weeks Sleep Strategy', summary: 'Sleep is challenging now. Focus on rest rather than perfect sleep.', content: 'At 35 weeks, finding any comfortable position is difficult. Accept that fragmented sleep is normal. Rest when possible — a 20-minute daytime rest improves energy more than tossing at night. Use bathroom trips as opportunities to stretch and change positions rather than sources of frustration. If racing thoughts keep you awake, keep a notebook by your bed to capture worries and to-do lists. Your body is preparing for newborn sleep patterns — this disrupted sleep has a purpose. Remember: you will sleep again. This phase ends.', source: 'GENERAL', tags: ['late pregnancy sleep', 'rest', 'third trimester', 'sleep strategy'] },
  { stageKey: 'preg_week_35', category: 'PLAY_ACTIVITIES', priority: 80, title: 'Packing Your Hospital Bag Together', summary: 'Involve your partner in packing as a bonding and preparation activity.', content: 'Pack by week 35-36 — babies can arrive early. Include: comfortable clothes for you (loose, easy for nursing), going-home outfit for baby (weather-appropriate), toiletries, phone charger with long cord, snacks for your partner, important documents (ID, insurance card, birth plan), and something comforting from home. Pack a separate small bag for labor with items you will want immediate access to. Do not overpack — most hospitals provide basics. The act of packing together makes the upcoming birth feel more real and manageable for both partners.', source: 'DEVELOPMENT', tags: ['hospital bag', 'birth preparation', 'labor planning', 'partner involvement'] },

  { stageKey: 'preg_week_39', category: 'PARENT_WELLBEING', priority: 85, title: 'The Waiting Game: Patience at Full Term', summary: 'You are officially full term. The waiting can be the hardest part.', content: 'At 39 weeks, every day feels like a week. Your baby is fully developed and could arrive at any time. Distract yourself with gentle activities: finish a book, watch favorite movies, spend time with your partner, prepare freezer meals. Avoid obsessively Googling labor signs. Trust your body and your baby. Membrane sweeping may be offered at your next appointment to encourage labor. Sex, walking, and nipple stimulation may help, but labor starts when your baby and body are ready. Use this waiting time for rest — it is the last quiet you will have for a while.', source: 'GENERAL', tags: ['full term', 'waiting for labor', 'patience', 'emotional preparation'] },
  { stageKey: 'preg_week_39', category: 'SLEEP', priority: 90, title: 'Differentiating Braxton Hicks from True Labor', summary: 'Knowing the difference between practice contractions and real labor reduces anxiety.', content: 'Braxton Hicks are irregular, do not increase in intensity, and often stop with position changes or hydration. True labor contractions become regular, stronger, and closer together over time. Time contractions for an hour: note start time, duration, and interval. True labor contractions do not stop with rest or water. Other signs of labor include bloody show (mucus plug), water breaking (may be a gush or trickle), and lower back pain that does not ease. When in doubt, call your provider. It is always better to be checked unnecessarily than to wait too long.', source: 'CLINICAL', tags: ['labor signs', 'Braxton Hicks', 'contractions', 'when to go to hospital'] },

  { stageKey: 'preg_week_40', category: 'PARENT_WELLBEING', priority: 90, title: 'Your Due Date Has Arrived: What Now?', summary: 'Only 5% of babies arrive on their due date. You are in good company.', content: 'Your due date is an estimate, not a deadline. Most first babies arrive between 40+5 and 41+2. Your provider will discuss options if you go past 41 weeks, which may include membrane sweeping or induction. Continue monitoring fetal movement. Stay active with walking. Rest and hydrate. If you are feeling pressure (internal or external) about being overdue, discuss this with your provider. Your body and baby know what they are doing. The average pregnancy lasts 40 weeks and 5 days for first-time parents. You are not late — your baby is simply on their own schedule.', source: 'GENERAL', tags: ['due date', 'overdue pregnancy', 'patience', 'birth timing'] },
  { stageKey: 'preg_week_40', category: 'SLEEP', priority: 90, title: 'Sleep and Rest During Early Labor', summary: 'If early labor begins, rest is your most important tool.', content: 'Early labor can last hours or days, especially for first-time parents. Rest between contractions even if you cannot sleep. Eat light, easily digestible foods. Stay hydrated. Distract yourself with movies, music, or gentle activities. Use relaxation techniques from your childbirth class. Conserve your energy for active labor, which requires significant physical effort. Your partner can help by protecting your rest: handling communications, managing the environment, and providing physical comfort. You are about to run a marathon — do not start depleted.', source: 'CLINICAL', tags: ['early labor', 'labor rest', 'energy conservation', 'birth preparation'] },

  // Additional general fills for weeks 23, 25, 27, 28, 31, 35
  { stageKey: 'preg_week_23', category: 'SLEEP', priority: 90, title: 'Pregnancy Pillows: Worth the Investment', summary: 'A good pregnancy pillow can transform your sleep quality.', content: 'Full-length U-shaped and C-shaped pregnancy pillows support your back, belly, and knees simultaneously. They reduce pressure on hips and lower back. Many parents report significantly better sleep after investing in a quality pregnancy pillow. They are also useful postpartum for comfortable nursing or bottle-feeding positions. If a full pillow seems excessive, a simple wedge under your belly combined with a regular pillow between your knees provides similar benefits at lower cost. Good sleep supports both your health and your baby\'s development.', source: 'GENERAL', tags: ['pregnancy pillow', 'sleep comfort', 'body support', 'sleep quality'] },
  { stageKey: 'preg_week_25', category: 'PARENT_WELLBEING', priority: 85, title: 'Creating Your Birth Preferences Document', summary: 'A flexible birth preferences document helps communicate your wishes.', content: 'Birth rarely follows a script, but a preferences document helps you think through options and communicate with your care team. Include preferences for: pain management, mobility during labor, monitoring, pushing positions, immediate postpartum care, newborn procedures, and feeding. Use positive language: "I would like to try" rather than "I do not want." Review with your provider in advance. Understand which options are available at your birth location. The best birth plan is one that prioritizes the health of both you and your baby while respecting your preferences where medically appropriate.', source: 'GENERAL', tags: ['birth plan', 'birth preferences', 'labor preparation', 'communication'] },
  { stageKey: 'preg_week_27', category: 'NUTRITION_FEEDING', priority: 90, title: 'Iron-Rich Foods for Third Trimester Energy', summary: 'Iron needs peak in the third trimester. Food sources matter.', content: 'Your blood volume has increased by 50%, requiring substantial iron. Best animal sources: lean red meat, poultry, eggs, and fish. Best plant sources: lentils, spinach, tofu, pumpkin seeds, and fortified cereals. Pair plant sources with vitamin C (citrus, bell peppers, tomatoes) to enhance absorption. Avoid tea and coffee with iron-rich meals — tannins block absorption. If your provider recommends iron supplements, take them with vitamin C and expect possible constipation. Increase fiber and water intake to manage this side effect.', source: 'CLINICAL', tags: ['iron', 'pregnancy nutrition', 'third trimester', 'anemia prevention'] },
  { stageKey: 'preg_week_28', category: 'NUTRITION_FEEDING', priority: 90, title: 'Hydration Strategies for Late Pregnancy', summary: 'Proper hydration prevents Braxton Hicks, reduces swelling, and supports amniotic fluid.', content: 'Aim for 8-10 glasses of water daily. If plain water is unappealing, try: infused water with lemon, cucumber, or berries; herbal teas (check safety during pregnancy); diluted juice; water-rich foods like watermelon, cucumbers, and oranges. Monitor urine color — pale yellow indicates good hydration. Dehydration can trigger Braxton Hicks contractions. Keep a water bottle visible as a reminder. If you are experiencing swelling, paradoxically, drinking more water helps your body release retained fluid. Limit caffeine to 200mg daily.', source: 'CLINICAL', tags: ['hydration', 'pregnancy water', 'swelling', 'amniotic fluid'] },
  { stageKey: 'preg_week_31', category: 'SLEEP', priority: 90, title: 'Shortness of Breath When Lying Down', summary: 'Difficulty breathing while lying flat is common in the third trimester.', content: 'Your growing uterus pushes against your diaphragm, reducing lung capacity. This is normal but uncomfortable. Sleep propped up on multiple pillows or in a semi-reclined position. If you wake gasping, sit up and take slow, deep breaths through your nose. Shortness of breath when lying down typically resolves immediately after birth when your diaphragm has room to expand. Contact your provider if you experience sudden, severe shortness of breath, chest pain, or racing heart — these can indicate more serious conditions.', source: 'CLINICAL', tags: ['shortness of breath', 'pregnancy breathing', 'sleep position', 'third trimester'] },
  { stageKey: 'preg_week_35', category: 'NUTRITION_FEEDING', priority: 90, title: 'Preparing Freezer Meals for Postpartum', summary: 'Batch cooking now saves you when you are too exhausted to cook later.', content: 'Spend a weekend in week 35-36 preparing freezer meals. Focus on one-handed foods you can eat while holding a newborn: burritos, muffins, soups in individual portions, casseroles, pre-made smoothie packs. Label everything with contents and date. Stock pantry with easy snacks: nuts, granola bars, dried fruit, crackers. If friends or family offer help, ask for meal deliveries rather than baby gifts. The immediate postpartum period is not the time for gourmet cooking. Nourishment is the goal, not presentation.', source: 'GENERAL', tags: ['freezer meals', 'postpartum preparation', 'meal prep', 'nutrition'] },
];

export async function seedBatch5FillCards() {
  console.log('Seeding batch 5 — filling thin stages...');

  // Seed toddler cards
  for (const card of toddlerCards) {
    const id = `seed_advice_${card.stageKey}_${card.title.replace(/[^a-zA-Z0-9]/g, '_').substring(0, 30)}`;
    await prisma.expertAdviceCard.upsert({
      where: { id },
      update: card,
      create: { id, ...card },
    });
  }
  console.log(`  Toddler cards: ${toddlerCards.length} upserted`);

  // Seed newborn fill cards
  for (const card of newbornFillCards) {
    const id = `seed_advice_${card.stageKey}_${card.title.replace(/[^a-zA-Z0-9]/g, '_').substring(0, 30)}`;
    await prisma.expertAdviceCard.upsert({
      where: { id },
      update: card,
      create: { id, ...card },
    });
  }
  console.log(`  Newborn fill cards: ${newbornFillCards.length} upserted`);

  // Seed pregnancy fill cards
  for (const card of pregnancyFillCards) {
    const id = `seed_advice_${card.stageKey}_${card.title.replace(/[^a-zA-Z0-9]/g, '_').substring(0, 30)}`;
    await prisma.expertAdviceCard.upsert({
      where: { id },
      update: card,
      create: { id, ...card },
    });
  }
  console.log(`  Pregnancy fill cards: ${pregnancyFillCards.length} upserted`);

  const total = toddlerCards.length + newbornFillCards.length + pregnancyFillCards.length;
  console.log(`Batch 5 complete: ${total} cards upserted across all thin stages.`);
}
