import { PrismaClient, AdviceCategory, ContentSource } from '@prisma/client';
const prisma = new PrismaClient();

/**
 * Batch 4 — Fill sparse newborn weeks (born_week_5, 7, 10, 11, 12).
 *
 * These 5 stages only have 2 cards each in the original seed, covering
 * only GROWTH_HEALTH and DEVELOPMENT. This batch adds the missing
 * NUTRITION_FEEDING, SLEEP, PLAY_ACTIVITIES, and PARENT_WELLBEING cards.
 * Total: ~25 cards across 5 stageKeys.
 */
export async function seedNewbornFillCards() {
  console.log('Seeding newborn fill-in advice cards (batch 4)...');

  const cards: Array<{
    stageKey: string;
    category: AdviceCategory;
    priority: number;
    title: string;
    summary: string;
    content: string;
    source: ContentSource;
    tags: string[];
  }> = [
    // ═══ born_week_5 (had 2 cards) ═══
    { stageKey: 'born_week_5', category: 'SLEEP', priority: 88, title: 'Newborn Sleep Cycles: Understanding Your Baby\'s Rhythms', summary: 'Your newborn alternates between active and quiet sleep — understanding these cycles helps you interpret their cues and avoid waking them unnecessarily.', content: 'Newborn sleep cycles are about 50 to 60 minutes long — much shorter than adult 90-minute cycles. A cycle begins with active REM sleep, during which your baby may twitch, make faces, flutter their eyelids, breathe irregularly, and even make small sounds. This is completely normal brain development at work. After about 20 to 30 minutes of active sleep, your baby transitions into quiet deep sleep, where they are still, breathe regularly, and are harder to wake. If you pick up or interact with your baby during active sleep, you may inadvertently wake them when they were simply cycling normally. Observe your baby before intervening: wait a minute or two to see if they settle back into sleep on their own. Learning to distinguish between active sleep and actually waking up is one of the most helpful skills for newborn parents — it can mean the difference between a baby who connects sleep cycles and one who is repeatedly woken.', source: 'DEVELOPMENT' as ContentSource, tags: ['newborn sleep', 'sleep cycles', 'REM sleep', 'active sleep', 'quiet sleep'] },
    { stageKey: 'born_week_5', category: 'NUTRITION_FEEDING', priority: 89, title: 'Growth Spurts at 5 Weeks: Cluster Feeding Explained', summary: 'If your baby suddenly wants to nurse every hour and seems never satisfied, congratulations — you are in a growth spurt.', content: 'The first major growth spurt typically arrives between 3 and 6 weeks. Your baby may want to feed every 60 to 90 minutes, sometimes for hours at a stretch, especially in the evening. This is called cluster feeding and it is NOT a sign that your milk supply is inadequate. Quite the opposite — it is your baby\'s brilliant biological strategy to increase your supply to meet their growing needs. Growth spurts typically last 2 to 3 days, after which feeding patterns usually settle. During a growth spurt: let your baby feed on demand, stay hydrated, eat well, rest when you can, and accept that you may be couch-bound for a couple of days. Your breasts may feel softer than usual — this is because your baby is draining them frequently, not because supply is dropping. If your baby is producing at least 6 to 8 wet diapers per day, they are getting enough milk. Formula-fed babies may also cluster feed during growth spurts — offer additional ounces as needed.', source: 'CLINICAL' as ContentSource, tags: ['growth spurt', 'cluster feeding', 'newborn feeding', 'milk supply', '5 weeks'] },
    { stageKey: 'born_week_5', category: 'PLAY_ACTIVITIES', priority: 82, title: 'Tummy Time at 5 Weeks: Building Strength Through Play', summary: 'Three to five minutes of tummy time, several times a day, builds the neck, shoulder, and core strength your baby needs for every future motor milestone.', content: 'At 5 weeks, your baby\'s neck strength has noticeably improved from birth. Tummy time is the single most important activity for developing the muscles needed for head control, rolling over, sitting up, and crawling. Aim for 3 to 5 minutes at a time, 2 to 3 times per day, totaling about 10 to 15 minutes daily. Place your baby on a firm, flat surface with a colorful mat or blanket. Get down on the floor at their eye level — your face is the most interesting thing in their world. Place high-contrast black-and-white cards or a safety mirror in front of them. If your baby fusses, try shorter sessions more frequently, or place them on your chest while you recline — this counts as tummy time too. Never leave your baby unsupervised during tummy time. If your baby falls asleep on their tummy, gently roll them onto their back — back to sleep is always the rule for unsupervised sleep.', source: 'DEVELOPMENT' as ContentSource, tags: ['tummy time', 'motor development', 'neck strength', 'play', '5 weeks'] },
    { stageKey: 'born_week_5', category: 'PARENT_WELLBEING', priority: 85, title: 'The 5-Week Check-In: How Are You Really Doing?', summary: 'At 5 weeks postpartum, the initial adrenaline has worn off — here is a compassionate self-assessment for new parents.', content: 'At 5 weeks postpartum, the initial flood of visitors, meals, and adrenaline has often receded, and the reality of round-the-clock newborn care has set in. This is a vulnerable time. Sleep deprivation is cumulative and real — it affects your mood, your patience, your ability to think clearly. How are you really doing? Are you eating enough? Drinking water? Showering occasionally? Do you have someone you can talk to honestly about the hard moments? The baby blues — tearfulness, irritability, mood swings — typically resolve by 2 to 3 weeks postpartum. If feelings of sadness, anxiety, hopelessness, detachment, or excessive worry persist or have begun after 3 weeks, this could be postpartum depression or anxiety. It is common, treatable, and not your fault. Call your provider. You do not need to suffer in silence. You deserve support, and your baby deserves a parent who is taking care of themselves.', source: 'DEVELOPMENT' as ContentSource, tags: ['postpartum', 'mental health', 'self-care', '5 weeks', 'postpartum depression'] },

    // ═══ born_week_7 (had 2 cards) ═══
    { stageKey: 'born_week_7', category: 'SLEEP', priority: 86, title: 'The Period of PURPLE Crying: What Every Parent Should Know', summary: 'Around 6 weeks, crying peaks — understanding the PURPLE period helps you survive it safely.', content: 'The Period of PURPLE Crying is a normal developmental phase when crying increases, beginning around 2 weeks, peaking at 6 to 8 weeks, and resolving around 3 to 4 months. PURPLE is an acronym: Peak of crying, Unexpected, Resists soothing, Pain-like face, Long lasting, Evening. During this period, your baby may cry inconsolably for hours, particularly in the late afternoon and evening. This is NOT your fault. It is NOT a sign that something is wrong. It is a normal, time-limited developmental phase. Strategies that sometimes help: the 5 S\'s — swaddling, side/stomach position (while held, not for sleep), shushing white noise, swinging or rhythmic motion, sucking on a pacifier or breast. Sometimes nothing works, and that is frustrating and exhausting. If you feel yourself reaching your limit, put the baby in a safe place — their crib, on their back, with nothing else in the crib — and walk away for 5 to 10 minutes. Scream into a pillow. Call your partner or a friend. Never, ever shake a baby — shaking can cause permanent brain damage or death in seconds.', source: 'CLINICAL' as ContentSource, tags: ['PURPLE crying', 'colic', 'inconsolable crying', 'shaken baby prevention', '7 weeks'] },
    { stageKey: 'born_week_7', category: 'NUTRITION_FEEDING', priority: 87, title: 'Paced Bottle Feeding: A Technique That Helps Prevent Overfeeding', summary: 'Whether you are feeding expressed milk or formula, paced bottle feeding mimics breastfeeding and helps your baby self-regulate.', content: 'Paced bottle feeding is a technique that gives your baby more control over feeding pace, mimicking the flow of breastfeeding. It reduces the risk of overfeeding, supports the development of self-regulation, and can help maintain breastfeeding if you are combination feeding. How to do it: hold your baby in a semi-upright position, supported — not lying flat. Hold the bottle horizontally rather than tipped, so milk does not flow by gravity alone. Touch the bottle nipple to your baby\'s lips and let them draw it in. Keep the nipple half-full of milk to reduce air intake. Tilt the bottle periodically to pause the flow — this mimics the natural pauses in breastfeeding. Switch sides mid-feed, as you would at the breast. Let your baby set the pace — a typical paced feed takes 15 to 20 minutes rather than the 5 to 10 minutes of a gravity-fed bottle. Watch for fullness cues: slowing down, turning away, relaxing hands. Never force your baby to finish a bottle.', source: 'DEVELOPMENT' as ContentSource, tags: ['paced feeding', 'bottle feeding', 'overfeeding prevention', 'newborn feeding', 'combination feeding'] },
    { stageKey: 'born_week_7', category: 'PLAY_ACTIVITIES', priority: 81, title: 'High-Contrast Play: What Your 7-Week-Old Can See', summary: 'Your baby\'s vision is developing rapidly — high-contrast patterns are exactly what their developing brain craves right now.', content: 'At 7 weeks, your baby can see objects about 20 to 30 centimeters away — roughly the distance to your face during feeding. They are especially drawn to high-contrast patterns: black and white, bold geometric shapes, and the human face. Create simple high-contrast cards using black marker on white paper: stripes, bullseyes, checkerboards, and simple faces. Hang them beside the changing table or during tummy time. Slowly move a card back and forth about 20 centimeters from your baby\'s face — they may begin tracking the movement with their eyes, an important visual-motor skill. Your face remains the most fascinating thing in their world: make exaggerated expressions, wide eyes, and big smiles. Your baby may begin to imitate facial expressions around this age — stick out your tongue and see what happens. Vision develops rapidly over the next months, and these simple activities support healthy visual development.', source: 'DEVELOPMENT' as ContentSource, tags: ['visual development', 'high-contrast', 'newborn vision', 'tracking', 'play'] },

    // ═══ born_week_10 (had 2 cards) ═══
    { stageKey: 'born_week_10', category: 'SLEEP', priority: 84, title: 'Drowsy But Awake: The Elusive Goal Explained', summary: 'You have probably heard to put your baby down drowsy but awake — here is what that actually means and how to practice it gently.', content: 'Drowsy but awake means putting your baby in their sleep space when they are calm and sleepy but not yet fully asleep. This helps them learn to fall asleep in the same place they will wake up, which can reduce startling and crying when they wake between sleep cycles. At 10 weeks, this is a practice to explore gently — not a rigid rule. Watch for your baby\'s early sleep cues: decreased activity, slower movements, staring off, less vocalizing, and the first eye rubs or yawns. This is the drowsy window. If you wait until they are crying, you have missed it. Place them in their crib or bassinet on their back. If they fuss, stay nearby and offer gentle shushing, patting, or a hand on their chest. If they escalate to crying, pick them up, soothe them fully, and try again another time. Some babies take to this easily; others need more support. There is no failure in soothing your baby to sleep — you are building trust and connection. The goal is simply to offer the opportunity to practice.', source: 'DEVELOPMENT' as ContentSource, tags: ['drowsy but awake', 'sleep training', 'newborn sleep', 'self-soothing', 'gentle parenting'] },
    { stageKey: 'born_week_10', category: 'NUTRITION_FEEDING', priority: 83, title: 'Vitamin D for Your Baby: The One Supplement You Shouldn\'t Skip', summary: 'The AAP recommends 400 IU of vitamin D daily for all breastfed and partially breastfed infants — here is why and how.', content: 'Breast milk is nutritionally complete in almost every way — with one exception: vitamin D. Human milk contains very little vitamin D, regardless of the breastfeeding parent\'s intake. The American Academy of Pediatrics recommends 400 international units (IU) of vitamin D drops daily for all breastfed and partially breastfed infants, starting in the first days of life. Formula-fed infants consuming less than 32 ounces per day also need supplementation. Infant vitamin D drops are widely available — most brands now formulate one drop to equal exactly 400 IU, making administration simple: place a drop on your clean finger and let your baby suck it, or on your nipple before latching. Vitamin D is critical for calcium absorption and bone mineralization. Deficiency can cause rickets, a bone-softening disease. It may also play a role in immune function. Continue supplementation until your child is consuming at least 32 ounces of vitamin D-fortified formula or milk daily, usually around 1 year.', source: 'CLINICAL' as ContentSource, tags: ['vitamin D', 'supplementation', 'breastfeeding', 'rickets', 'newborn nutrition'] },
    { stageKey: 'born_week_10', category: 'PARENT_WELLBEING', priority: 84, title: 'Returning to Work: Preparing Emotionally and Logistically', summary: 'If your parental leave is ending soon, the transition back to work brings a complex mix of emotions — preparation helps.', content: 'Returning to work after having a baby is one of the most significant transitions a parent navigates. You may feel grief about leaving your baby, relief about adult interaction, anxiety about pumping logistics, guilt about any of the above, or all of these simultaneously — all valid. Start preparing now: if you are pumping, practice with your pump and build a small freezer stash. Visit your childcare provider with your baby before the first day. Create a shared calendar with your partner showing drop-offs, pickups, and backup care. Talk honestly about how household responsibilities will shift when you are both working. Set expectations with your employer: will you phase back gradually, work flexible hours, or need pumping breaks? Many parents find the anticipation of returning to work is harder than the reality. The first week is the hardest. By week three, a new normal begins to emerge. Your baby will be okay — you are modeling work ethic, purpose, and identity for them.', source: 'DEVELOPMENT' as ContentSource, tags: ['returning to work', 'parental leave', 'pumping', 'childcare', 'work-life balance'] },

    // ═══ born_week_11 (had 2 cards) ═══
    { stageKey: 'born_week_11', category: 'SLEEP', priority: 85, title: 'The 4-Month Sleep Regression: It Starts Earlier Than You Think', summary: 'Around 3 to 4 months, your baby\'s sleep architecture fundamentally changes — and some babies show signs of this transition as early as 11 weeks.', content: 'The 4-month sleep regression is actually a developmental progression — your baby\'s sleep is maturing from newborn patterns to adult-like sleep cycles. Newborns enter sleep through REM; after this transition, they enter through non-REM, just like adults. This means they now wake briefly between sleep cycles and need to learn to connect them. Signs this transition has begun: your previously decent sleeper suddenly wakes every 45 to 90 minutes, has difficulty being put down after feeding to sleep, catnaps of exactly one sleep cycle, and increased fussiness at bedtime. This is NOT your fault and NOT a sign that you created bad habits. It is neurological development. Strategies: consistent bedtime routines, putting baby down drowsy but awake when possible, and practicing independent sleep skills during the day. This phase can last 2 to 6 weeks. It requires patience, not fixing.', source: 'DEVELOPMENT' as ContentSource, tags: ['sleep regression', '4 month regression', 'sleep cycles', 'baby sleep', 'neurological development'] },
    { stageKey: 'born_week_11', category: 'PLAY_ACTIVITIES', priority: 80, title: 'Babywearing: The Benefits of Keeping Your Baby Close', summary: 'Carrying your baby in a wrap or carrier supports bonding, reduces crying, and frees your hands — here is how to do it safely.', content: 'Babywearing — carrying your baby in a soft structured carrier, wrap, or sling — has documented benefits: babies who are carried cry less, are more likely to breastfeed successfully, and experience better physiological regulation. The rhythmic motion and closeness mimic the womb environment. For parents, it means hands-free mobility to eat, work, care for other children, or simply move through the world. Safety is paramount. Follow the T.I.C.K.S. rule: Tight (carrier holds baby snugly), In view (you can always see baby\'s face), Close enough to kiss (baby\'s head is at chin level), Keep chin off chest (airway must stay open), Supported back (baby\'s back is in a natural position, not slumped). Baby\'s legs should be in an M position — knees higher than bottom — to support healthy hip development. Start with short wearing sessions as your baby gets used to it. At 11 weeks, your baby likely has enough neck control to face inward in a soft structured carrier.', source: 'DEVELOPMENT' as ContentSource, tags: ['babywearing', 'baby carrier', 'attachment', 'bonding', 'safe carrying'] },

    // ═══ born_week_12 (had 2 cards) ═══
    { stageKey: 'born_week_12', category: 'SLEEP', priority: 84, title: 'Creating a Bedtime Routine Your Baby Will Recognize', summary: 'A consistent bedtime routine is one of the most powerful tools you have for supporting healthy sleep.', content: 'Babies thrive on predictability. A consistent bedtime routine signals to your baby that sleep is coming, reduces cortisol, and supports the development of their circadian rhythm. By 12 weeks, your baby is producing their own melatonin and can begin to learn sleep associations. A simple effective routine: bath or warm washcloth wipe-down, gentle massage with baby-safe lotion, fresh diaper, pajamas or sleep sack, feeding in a dimly lit room, a short book or lullaby, and a consistent sleep phrase like "I love you, it is time to sleep now". Keep the routine to 20 to 30 minutes and do the same steps in the same order every night. Dim the lights 30 minutes before you start — darkness stimulates melatonin production. White noise, approximately as loud as a shower, can help block startling sounds and become a sleep cue. The same routine works for naps in a condensed version. Your baby may not sleep through the night yet — that is developmentally normal. The routine itself is the gift.', source: 'DEVELOPMENT' as ContentSource, tags: ['bedtime routine', 'baby sleep', 'sleep associations', 'circadian rhythm', '12 weeks'] },
    { stageKey: 'born_week_12', category: 'PARENT_WELLBEING', priority: 87, title: 'Your Relationship After Baby: The First 3 Months', summary: 'Research shows most couples experience a dip in relationship satisfaction after a baby — understanding why helps you navigate it together.', content: 'The transition to parenthood is one of the most significant stressors a relationship can face. The combination of sleep deprivation, radically shifted roles, reduced time for connection, and the overwhelming responsibility of keeping a tiny human alive strains even the strongest partnerships. This is normal. It does not mean your relationship is broken. Practical strategies that help: schedule 15 minutes daily to connect without phones or baby talk (yes, schedule it — spontaneity is a luxury of the well-rested), express appreciation for specific things your partner did that day, acknowledge that you are both doing your best under hard conditions, and assume good intent when you are both tired. Split overnight care intentionally — one shift each allows each person at least 4 to 5 hours of consolidated sleep. The lowest point for most couples is around 3 to 4 months. Things typically begin improving after sleep consolidates. If you are really struggling, couples therapy is not a last resort — it is an investment in your family.', source: 'DEVELOPMENT' as ContentSource, tags: ['relationships', 'postpartum', 'couples', 'partnership', 'communication'] },
  ];

  for (const card of cards) {
    await prisma.expertAdviceCard.upsert({
      where: { id: `seed_advice_${card.stageKey}_${card.title.replace(/[^a-zA-Z0-9]/g, '_').substring(0, 30)}` },
      update: card,
      create: { id: `seed_advice_${card.stageKey}_${card.title.replace(/[^a-zA-Z0-9]/g, '_').substring(0, 30)}`, ...card },
    });
  }

  console.log(`Seeded ${cards.length} newborn fill-in advice cards (batch 4 newborn)`);
  return cards.length;
}
