-- Add syncStatus columns for offline sync engine.
-- Generated by hand: the auto-generated `prisma migrate diff` produced a
-- 200+ line file that tried to recreate every enum/table that already
-- exists in Neon (because the diff was run against a fresh empty DB).
-- This minimal file just adds the 4 missing columns.
ALTER TABLE "Milestone"     ADD COLUMN "syncStatus" TEXT NOT NULL DEFAULT 'SYNCED';
ALTER TABLE "FeedLog"       ADD COLUMN "syncStatus" TEXT NOT NULL DEFAULT 'SYNCED';
ALTER TABLE "HealthRecord"  ADD COLUMN "syncStatus" TEXT NOT NULL DEFAULT 'SYNCED';
ALTER TABLE "SleepLog"      ADD COLUMN "syncStatus" TEXT NOT NULL DEFAULT 'SYNCED';
