export enum AuditEvent {
  // Auth
  USER_REGISTERED = 'USER_REGISTERED',
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',

  // BabyMon
  BABYMON_CREATED = 'BABYMON_CREATED',
  BABYMON_UPDATED = 'BABYMON_UPDATED',
  BABYMON_DELETED = 'BABYMON_DELETED',

  // Linked accounts
  ACCESS_GRANTED = 'ACCESS_GRANTED',
  ACCESS_REVOKED = 'ACCESS_REVOKED',

  // Core logging
  MILESTONE_CREATED = 'MILESTONE_CREATED',
  MILESTONE_UPDATED = 'MILESTONE_UPDATED',
  FEED_LOG_CREATED = 'FEED_LOG_CREATED',
  FEED_LOG_UPDATED = 'FEED_LOG_UPDATED',
  FEED_LOG_DELETED = 'FEED_LOG_DELETED',
  HEALTH_RECORD_CREATED = 'HEALTH_RECORD_CREATED',
  HEALTH_RECORD_UPDATED = 'HEALTH_RECORD_UPDATED',
  HEALTH_RECORD_DELETED = 'HEALTH_RECORD_DELETED',

  // Gamification
  BADGE_EARNED = 'BADGE_EARNED',
  EVOLUTION_STAGE_CHANGED = 'EVOLUTION_STAGE_CHANGED',

  // Subscription
  SUBSCRIPTION_CREATED = 'SUBSCRIPTION_CREATED',
  SUBSCRIPTION_CANCELLED = 'SUBSCRIPTION_CANCELLED',
  SUBSCRIPTION_RENEWED = 'SUBSCRIPTION_RENEWED',
}