// Local type declaration for Prisma enums that don't exist in schema.prisma model fields
// and therefore aren't generated by Prisma Client.
// UserRole is used in code but the User.role field is String (not an enum).

export type UserRole = 'USER' | 'ADMIN';
